resources:
  - kind: schedules
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"opsGenieSchedule"'
          properties:
            description: .description
            enabled: .enabled
            oncall: .oncall_users
            rotations: .rotations
  - kind: alerts
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .message
          blueprint: '"opsGenieAlert"'
          properties:
            status: .status
            acknowledged: .acknowledged
            responders: .responders
            priority: .priority
            sourceName: .source
            tags: .tags
            createdBy: .owner
            createdAt: .createdAt
            updatedAt: .updatedAt