resources:
  - kind: projects
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .attributes.name
          blueprint: '"snykProject"'
          properties:
            url: ("https://app.snyk.io/org/" + .relationships.organization.data.id + "/project/" + .id | tostring)
            owner: ._owner.email
            businessCriticality: .attributes.business_criticality
            environment: .attributes.environment
            lifeCycle: .attributes.lifecycle
            highOpenVulnerabilities: .meta.latest_issue_counts.high
            mediumOpenVulnerabilities: .meta.latest_issue_counts.medium
            lowOpenVulnerabilities: .meta.latest_issue_counts.low
            importedBy: ._importer.email
            tags: .attributes.tags
            targetOrigin: .attributes.origin
            targetUrl: .relationships.target.data.attributes.url
  - kind: vulnerabilities
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .issueData.id
          title: .issueData.title
          blueprint: '"snykVulnerability"'
          properties:
            score: .priorityScore
            packageName: .pkgName
            packageVersions: .pkgVersions
            type: .issueType
            severity: .issueData.severity
            url: .issueData.url
            language: .issueData.language
            publicationTime: .issueData.publicationTime
            isPatched: .isPatched
          relations:
            snykProject: .links.paths | capture("/project/(?<project_id>[^/]+)/history/") | .project_id
