resources:
  - kind: cloudAnalysis
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"sonarCloudAnalyses"'
          identifier: .project_key
          title: .project_name
          properties:
              serverUrl: .server_url
              projectUrl: .project_url
              branchName: .branch_name
              branchType: .branch_type
              qualityGateName: .quality_gate_name
              qualityGateStatus: .quality_gate_status
              qualityGateConditions: .quality_gate_conditions
