resources:
  - kind: projects
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"sonarqubeProject"'
          identifier: .key
          title: .name
          properties:
              organization: .organization
              visibility: .visibility
              tags: .tags
  - kind: qualitygates
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"sonarqubeQualityGate"'
          identifier: .id
          title: .name
          properties:
              status: .status
              conditions: .conditions